export type CatalogStatus = 'FOUNDATION' | 'MIGRATING' | 'LEGACY';

export interface UiCatalogItem {
  id: string;
  name: string;
  category: string;
  exportName: string;
  filePath: string;
  status: CatalogStatus;
  statusText: string;
  auditNotes: string;
  demoType?: 'modal' | 'drawer';
}

/**
 * The catalog is deliberately a typed migration manifest, not a self-awarded
 * component-quality score. The CI contract validates every exported entry.
 */
export const UI_CATALOG_ITEMS: readonly UiCatalogItem[] = [
  {
    id: 'AppIcon',
    name: 'AppIcon',
    category: 'Foundation',
    exportName: 'AppIcon',
    filePath: 'apps/web/components/ui/AppIcon.tsx',
    status: 'FOUNDATION',
    statusText: 'Nền tảng sẵn sàng',
    auditNotes: 'Adapter Lucide chuẩn hóa icon, stroke và accessibility cho product UI mới.',
  },
  {
    id: 'ContentSurface',
    name: 'ContentSurface',
    category: 'Foundation',
    exportName: 'ContentSurface',
    filePath: 'apps/web/components/ui/ContentSurface.tsx',
    status: 'FOUNDATION',
    statusText: 'Nền tảng sẵn sàng',
    auditNotes: 'Bề mặt nội dung dùng token theme và density chung.',
  },
  {
    id: 'PageHeader',
    name: 'PageHeader',
    category: 'Foundation',
    exportName: 'PageHeader',
    filePath: 'apps/web/components/ui/PageHeader.tsx',
    status: 'FOUNDATION',
    statusText: 'Nền tảng sẵn sàng',
    auditNotes: 'Khung hierarchy cho tiêu đề, mô tả và action trang.',
  },
  {
    id: 'PageToolbar',
    name: 'PageToolbar',
    category: 'Foundation',
    exportName: 'PageToolbar',
    filePath: 'apps/web/components/ui/PageToolbar.tsx',
    status: 'MIGRATING',
    statusText: 'Đang migration',
    auditNotes: 'Toolbar chuẩn đã có, nhưng các legacy page còn bypass.',
  },
  {
    id: 'SearchField',
    name: 'SearchField',
    category: 'Filters & period',
    exportName: 'SearchField',
    filePath: 'apps/web/components/ui/SearchField.tsx',
    status: 'FOUNDATION',
    statusText: 'Nền tảng sẵn sàng',
    auditNotes: 'Search shell dùng AppIcon và density token; nút submit luôn đạt vùng chạm trên phone.',
  },
  {
    id: 'CollapsibleSearchField',
    name: 'CollapsibleSearchField',
    category: 'Filters & period',
    exportName: 'CollapsibleSearchField',
    filePath: 'apps/web/components/ui/CollapsibleSearchField.tsx',
    status: 'FOUNDATION',
    statusText: 'Nền tảng sẵn sàng',
    auditNotes: 'Search thu gọn theo mặc định, mở và focus bằng một icon action; ô trống tự thu lại khi rời focus.',
  },
  {
    id: 'StatusTag',
    name: 'StatusTag',
    category: 'Feedback & state',
    exportName: 'StatusTag',
    filePath: 'apps/web/components/ui/StatusTag.tsx',
    status: 'MIGRATING',
    statusText: 'Đang migration',
    auditNotes: 'Sẽ thay dần status Tag tự dựng theo từng domain.',
  },
  {
    id: 'StatePanel',
    name: 'StatePanel',
    category: 'Feedback & state',
    exportName: 'StatePanel',
    filePath: 'apps/web/components/ui/StatePanel.tsx',
    status: 'MIGRATING',
    statusText: 'Đang migration',
    auditNotes: 'Chuẩn loading, empty và error cho data surface.',
  },
  {
    id: 'FeaturePage',
    name: 'FeaturePage',
    category: 'Page assemblies',
    exportName: 'FeaturePage',
    filePath: 'apps/web/components/ui/FeaturePage.tsx',
    status: 'MIGRATING',
    statusText: 'Đang migration',
    auditNotes: 'Khung chung cho workspace không thuộc CRUD hoặc report mặc định.',
  },
  {
    id: 'ResourceListPage',
    name: 'ResourceListPage',
    category: 'Page assemblies',
    exportName: 'ResourceListPage',
    filePath: 'apps/web/components/ui/ResourceListPage.tsx',
    status: 'MIGRATING',
    statusText: 'Đang migration',
    auditNotes: 'Assembly chuẩn cho CRUD/list với toolbar, KPI và data section.',
  },
  {
    id: 'ReportPage',
    name: 'ReportPage',
    category: 'Page assemblies',
    exportName: 'ReportPage',
    filePath: 'apps/web/components/ui/ReportPage.tsx',
    status: 'MIGRATING',
    statusText: 'Đang migration',
    auditNotes: 'Assembly chuẩn cho report/leaderboard với period navigator responsive.',
  },
  {
    id: 'FeatureToolbar',
    name: 'FeatureToolbar',
    category: 'Page assemblies',
    exportName: 'FeatureToolbar',
    filePath: 'apps/web/components/ui/FeatureToolbar.tsx',
    status: 'MIGRATING',
    statusText: 'Đang migration',
    auditNotes: 'Shell filter/action responsive, dùng lại cho report và operational page.',
  },
  {
    id: 'MetricGrid',
    name: 'MetricGrid',
    category: 'Data',
    exportName: 'MetricGrid',
    filePath: 'apps/web/components/ui/MetricGrid.tsx',
    status: 'MIGRATING',
    statusText: 'Đang migration',
    auditNotes: 'Grid KPI chung thay cho statistic/card page-local.',
  },
  {
    id: 'DataSection',
    name: 'DataSection',
    category: 'Data',
    exportName: 'DataSection',
    filePath: 'apps/web/components/ui/DataSection.tsx',
    status: 'MIGRATING',
    statusText: 'Đang migration',
    auditNotes: 'Section có loading, empty và error contract.',
  },
  {
    id: 'DataTable',
    name: 'DataTable',
    category: 'Data',
    exportName: 'DataTable',
    filePath: 'apps/web/components/ui/DataTable.tsx',
    status: 'MIGRATING',
    statusText: 'Đang migration',
    auditNotes: 'Table responsive với pagination contract và mobile renderer.',
  },
  {
    id: 'MobileRecordList',
    name: 'MobileRecordList',
    category: 'Data',
    exportName: 'MobileRecordList',
    filePath: 'apps/web/components/ui/MobileRecordList.tsx',
    status: 'MIGRATING',
    statusText: 'Đang migration',
    auditNotes: 'Record-list fallback cho phone thay vì ép table desktop.',
  },
  {
    id: 'ReportPeriodNavigator',
    name: 'ReportPeriodNavigator',
    category: 'Filters & period',
    exportName: 'ReportPeriodNavigator',
    filePath: 'apps/web/components/ui/ReportPeriodNavigator.tsx',
    status: 'MIGRATING',
    statusText: 'Đang migration',
    auditNotes: 'Điều hướng Tháng/Tuần/Ngày với icon và touch target chuẩn.',
  },
  {
    id: 'ToolbarFilterDisclosure',
    name: 'ToolbarFilterDisclosure',
    category: 'Filters & period',
    exportName: 'ToolbarFilterDisclosure',
    filePath: 'apps/web/components/ui/ToolbarFilterDisclosure.tsx',
    status: 'MIGRATING',
    statusText: 'Đang migration',
    auditNotes: 'Chuyển filter vào drawer trên mobile mà giữ semantic control.',
  },
  {
    id: 'ToolbarToggle',
    name: 'ToolbarToggle',
    category: 'Filters & period',
    exportName: 'ToolbarToggle',
    filePath: 'apps/web/components/ui/ToolbarToggle.tsx',
    status: 'FOUNDATION',
    statusText: 'Nền tảng sẵn sàng',
    auditNotes: 'Toggle có kích thước và label theo density token.',
  },
  {
    id: 'ResponsiveFormGrid',
    name: 'ResponsiveFormGrid',
    category: 'Forms & overlays',
    exportName: 'ResponsiveFormGrid',
    filePath: 'apps/web/components/ui/ResponsiveFormGrid.tsx',
    status: 'MIGRATING',
    statusText: 'Đang migration',
    auditNotes: 'Grid field responsive cho form/filter.',
  },
  {
    id: 'EntityForm',
    name: 'EntityForm',
    category: 'Forms & overlays',
    exportName: 'EntityForm',
    filePath: 'apps/web/components/ui/EntityForm.tsx',
    status: 'MIGRATING',
    statusText: 'Đang migration',
    auditNotes: 'Form CRUD chung giữ field/grid contract.',
  },
  {
    id: 'EntityFormDrawer',
    name: 'EntityFormDrawer',
    category: 'Forms & overlays',
    exportName: 'EntityFormDrawer',
    filePath: 'apps/web/components/ui/EntityFormDrawer.tsx',
    status: 'MIGRATING',
    statusText: 'Đang migration',
    auditNotes: 'Create/edit drawer full-screen trên phone, sticky footer chuẩn.',
  },
  {
    id: 'AdaptiveOverlay',
    name: 'AdaptiveOverlay',
    category: 'Forms & overlays',
    exportName: 'AdaptiveModal',
    filePath: 'apps/web/components/ui/AdaptiveOverlay.tsx',
    status: 'MIGRATING',
    statusText: 'Đang migration',
    auditNotes: 'Modal/drawer intent-based với responsive width contract.',
  },
  {
    id: 'HeaderIconButton',
    name: 'HeaderIconButton',
    category: 'Shell',
    exportName: 'HeaderIconButton',
    filePath: 'apps/web/components/ui/HeaderIconButton.tsx',
    status: 'FOUNDATION',
    statusText: 'Nền tảng sẵn sàng',
    auditNotes: 'Header action giữ target, icon optical box và accessible name thống nhất.',
  },
  {
    id: 'HeaderActionIndicator',
    name: 'HeaderActionIndicator',
    category: 'Shell',
    exportName: 'HeaderActionIndicator',
    filePath: 'apps/web/components/ui/HeaderActionIndicator.tsx',
    status: 'FOUNDATION',
    statusText: 'Nền tảng sẵn sàng',
    auditNotes: 'Status/count indicator không làm sai geometry của header action.',
  },
] as const;
