-- DropForeignKey
ALTER TABLE `crm_academy_workshop_equipment_template_package_images` DROP FOREIGN KEY `crm_academy_equipment_tpl_img_fk`;

-- DropForeignKey
ALTER TABLE `crm_academy_workshop_equipment_template_packages` DROP FOREIGN KEY `crm_academy_equipment_tpl_pkg_fk`;

-- DropForeignKey
ALTER TABLE `crm_academy_workshop_equipment_templates` DROP FOREIGN KEY `crm_academy_equipment_tpl_creator_fk`;

-- DropForeignKey
ALTER TABLE `crm_inbox_plan_jobs` DROP FOREIGN KEY `crm_inbox_plan_jobs_report_id_fkey`;

-- DropForeignKey
ALTER TABLE `crm_request_classification_job_attachments` DROP FOREIGN KEY `request_classification_attachment_job_fkey`;

-- DropForeignKey
ALTER TABLE `crm_request_classification_jobs` DROP FOREIGN KEY `request_classification_reporter_fkey`;

-- DropForeignKey
ALTER TABLE `crm_request_classifier_worker_health_transitions` DROP FOREIGN KEY `request_classifier_worker_transition_worker_fkey`;

-- DropIndex
DROP INDEX `crm_inbox_plan_jobs_report_id_event_kind_event_version_key` ON `crm_inbox_plan_jobs`;

-- DropIndex
-- The composite assignee/status index already supports this foreign key; the
-- imported baseline intentionally does not retain the redundant single-column
-- index generated by the original migration.
DROP INDEX `crm_academy_follow_up_tasks_assignee_staff_id_fkey` ON `crm_academy_follow_up_tasks`;

-- AlterTable
ALTER TABLE `crm_academy_workshop_equipment_packages` MODIFY `is_available` tinyint(1) NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE `crm_academy_workshop_equipment_template_packages` MODIFY `is_available` tinyint(1) NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE `crm_academy_workshop_menu_items` MODIFY `is_available` tinyint(1) NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE `crm_academy_workshop_menu_template_items` MODIFY `is_available` tinyint(1) NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE `crm_academy_workshops` ADD COLUMN `registration_code` VARCHAR(48) NULL,
    ADD COLUMN `registration_open` BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE `crm_bug_report_resolutions` MODIFY `updated_at` DATETIME(0) NOT NULL;

-- AlterTable
ALTER TABLE `crm_bug_reports` MODIFY `updated_at` DATETIME(0) NOT NULL;

-- AlterTable
ALTER TABLE `crm_departments` MODIFY `updated_at` DATETIME(0) NOT NULL;

-- AlterTable
ALTER TABLE `crm_inbox_implementation_jobs` ADD COLUMN `checkpoint_count` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `execution_owner` VARCHAR(16) NOT NULL DEFAULT 'IDE',
    ADD COLUMN `ide_handoff_revoked_at` DATETIME(0) NULL,
    ADD COLUMN `ide_provisioning_attempt_count` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `ide_provisioning_failure_code` VARCHAR(100) NULL,
    ADD COLUMN `ide_provisioning_lease_expires_at` DATETIME(0) NULL,
    ADD COLUMN `ide_provisioning_lease_token` VARCHAR(64) NULL,
    ADD COLUMN `ide_provisioning_request_id` VARCHAR(36) NULL,
    ADD COLUMN `ide_provisioning_state` VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `ide_receipt_nonce` VARCHAR(64) NULL,
    ADD COLUMN `ide_task_bound_at` DATETIME(0) NULL,
    ADD COLUMN `ide_task_id` VARCHAR(160) NULL,
    ADD COLUMN `last_progress_at` DATETIME(0) NULL,
    ADD COLUMN `progress_count` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `progress_label` VARCHAR(160) NULL,
    MODIFY `execution_phase` varchar(32) NOT NULL DEFAULT 'IDE_HANDOFF_READY',
    MODIFY `updated_at` DATETIME(0) NOT NULL;

-- AlterTable
ALTER TABLE `crm_inbox_implementation_worker_lock` MODIFY `id` int(11) NOT NULL DEFAULT 1,
    MODIFY `updated_at` DATETIME(0) NOT NULL;

-- AlterTable
ALTER TABLE `crm_menu_access_policies` MODIFY `updated_at` DATETIME(0) NOT NULL;

-- AlterTable
ALTER TABLE `crm_request_classification_jobs` MODIFY `updated_at` DATETIME(0) NOT NULL;

-- AlterTable
ALTER TABLE `crm_request_classification_worker_heartbeats` MODIFY `updated_at` DATETIME(0) NOT NULL;

-- AlterTable
ALTER TABLE `crm_request_classifier_worker_health` MODIFY `updated_at` DATETIME(0) NOT NULL;

-- AlterTable
ALTER TABLE `crm_ui_experience_activations` MODIFY `updated_at` DATETIME(0) NOT NULL;

-- AlterTable
ALTER TABLE `crm_ui_experience_metrics` MODIFY `updated_at` DATETIME(0) NOT NULL;

-- CreateTable
CREATE TABLE `crm_experience_journal_events` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `fingerprint` CHAR(64) NOT NULL,
    `category` VARCHAR(12) NOT NULL,
    `severity` VARCHAR(12) NOT NULL,
    `component` VARCHAR(80) NOT NULL,
    `code` VARCHAR(100) NOT NULL,
    `summary` TEXT NOT NULL,
    `report_id` INTEGER NULL,
    `job_id` VARCHAR(36) NULL,
    `release_commit` VARCHAR(64) NULL,
    `metadata_json` TEXT NULL,
    `retention_expires_at` DATETIME(0) NOT NULL,
    `occurred_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `crm_experience_journal_events_category_severity_occurred_at_idx`(`category` ASC, `severity` ASC, `occurred_at` ASC),
    INDEX `crm_experience_journal_events_fingerprint_occurred_at_idx`(`fingerprint` ASC, `occurred_at` ASC),
    INDEX `crm_experience_journal_events_report_id_occurred_at_idx`(`report_id` ASC, `occurred_at` ASC),
    INDEX `crm_experience_journal_events_retention_expires_at_idx`(`retention_expires_at` ASC),
    PRIMARY KEY (`id` ASC)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `crm_experience_journal_fingerprints` (
    `fingerprint` CHAR(64) NOT NULL,
    `category` VARCHAR(12) NOT NULL,
    `severity` VARCHAR(12) NOT NULL,
    `component` VARCHAR(80) NOT NULL,
    `code` VARCHAR(100) NOT NULL,
    `summary` TEXT NOT NULL,
    `occurrence_count` INTEGER NOT NULL DEFAULT 0,
    `first_occurred_at` DATETIME(0) NOT NULL,
    `last_occurred_at` DATETIME(0) NOT NULL,
    `triage_status` VARCHAR(16) NOT NULL DEFAULT 'OPEN',
    `triage_note` TEXT NULL,
    `triaged_by_staff_id` INTEGER NULL,
    `triaged_at` DATETIME(0) NULL,

    INDEX `crm_experience_journal_fingerprints_category_severity_last_o_idx`(`category` ASC, `severity` ASC, `last_occurred_at` ASC),
    INDEX `crm_experience_journal_fingerprints_triage_status_last_occur_idx`(`triage_status` ASC, `last_occurred_at` ASC),
    PRIMARY KEY (`fingerprint` ASC)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateIndex
CREATE UNIQUE INDEX `crm_academy_workshops_registration_code_key` ON `crm_academy_workshops`(`registration_code` ASC);

-- CreateIndex
CREATE INDEX `crm_inbox_implementation_jobs_ide_provisioning_request_id_idx` ON `crm_inbox_implementation_jobs`(`ide_provisioning_request_id` ASC);

-- CreateIndex
CREATE INDEX `crm_inbox_implementation_jobs_ide_provisioning_state_ide_pro_idx` ON `crm_inbox_implementation_jobs`(`ide_provisioning_state` ASC, `ide_provisioning_lease_expires_at` ASC);

-- CreateIndex
CREATE INDEX `crm_inbox_implementation_jobs_ide_task_id_idx` ON `crm_inbox_implementation_jobs`(`ide_task_id` ASC);

-- CreateIndex
CREATE UNIQUE INDEX `crm_inbox_plan_jobs_report_id_event_version_key` ON `crm_inbox_plan_jobs`(`report_id` ASC, `event_version` ASC);

-- AddForeignKey
ALTER TABLE `crm_academy_workshop_equipment_template_package_images` ADD CONSTRAINT `crm_academy_workshop_equipment_template_package_images_temp_fkey` FOREIGN KEY (`template_package_id`) REFERENCES `crm_academy_workshop_equipment_template_packages`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `crm_academy_workshop_equipment_template_packages` ADD CONSTRAINT `crm_academy_workshop_equipment_template_packages_template_i_fkey` FOREIGN KEY (`template_id`) REFERENCES `crm_academy_workshop_equipment_templates`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `crm_academy_workshop_equipment_templates` ADD CONSTRAINT `crm_academy_workshop_equipment_templates_created_by_staff_i_fkey` FOREIGN KEY (`created_by_staff_id`) REFERENCES `crm_staff`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `crm_inbox_plan_jobs` ADD CONSTRAINT `crm_inbox_plan_jobs_report_id_fkey` FOREIGN KEY (`report_id`) REFERENCES `crm_bug_reports`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `crm_request_classification_job_attachments` ADD CONSTRAINT `crm_request_classification_job_attachments_job_id_fkey` FOREIGN KEY (`job_id`) REFERENCES `crm_request_classification_jobs`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `crm_request_classification_jobs` ADD CONSTRAINT `crm_request_classification_jobs_reporter_staff_id_fkey` FOREIGN KEY (`reporter_staff_id`) REFERENCES `crm_staff`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `crm_request_classifier_worker_health_transitions` ADD CONSTRAINT `crm_request_classifier_worker_health_transitions_worker_id_fkey` FOREIGN KEY (`worker_id`) REFERENCES `crm_request_classifier_worker_health`(`worker_id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- RenameIndex
ALTER TABLE `crm_inbox_implementation_jobs` RENAME INDEX `crm_inbox_implementation_jobs_lease_expires_idx` TO `crm_inbox_implementation_jobs_lease_expires_at_idx`;

-- RenameIndex
ALTER TABLE `crm_inbox_implementation_jobs` RENAME INDEX `crm_inbox_implementation_jobs_status_expires_idx` TO `crm_inbox_implementation_jobs_status_expires_at_idx`;

-- RenameIndex
ALTER TABLE `crm_request_classification_job_attachments` RENAME INDEX `request_classification_attachment_job_created_idx` TO `crm_request_classification_job_attachments_job_id_created_at_idx`;

-- RenameIndex
ALTER TABLE `crm_request_classification_job_attachments` RENAME INDEX `request_classification_attachment_storage_path_key` TO `crm_request_classification_job_attachments_storage_path_key`;

-- RenameIndex
ALTER TABLE `crm_request_classification_jobs` RENAME INDEX `request_classification_lease_expires_idx` TO `crm_request_classification_jobs_lease_expires_at_idx`;

-- RenameIndex
ALTER TABLE `crm_request_classification_jobs` RENAME INDEX `request_classification_reporter_created_idx` TO `crm_request_classification_jobs_reporter_staff_id_created_at_idx`;

-- RenameIndex
ALTER TABLE `crm_request_classification_jobs` RENAME INDEX `request_classification_status_expires_idx` TO `crm_request_classification_jobs_status_expires_at_idx`;

-- RenameIndex
ALTER TABLE `crm_request_classification_worker_heartbeats` RENAME INDEX `request_classification_worker_last_seen_idx` TO `crm_request_classification_worker_heartbeats_last_seen_at_idx`;
