'use client';

import React, { useState, useEffect, useCallback } from 'react';
import { Table, Button, Space, Tag, InputNumber, Tooltip, message, Typography } from 'antd';
import { ReloadOutlined, ThunderboltOutlined, EditOutlined, CheckOutlined, CloseOutlined } from '@ant-design/icons';
import { useTheme } from '../../../../context/ThemeContext';
import { apiClient } from '../../../../lib/api-client';
import { LashTypeBenchmark } from '@mos-lab/shared';

const { Text } = Typography;

// ─── Style color map ────────────────────────────────────────────────────────

const STYLE_COLORS: Record<string, string> = {
  Classic: '#52c41a',
  Mink: '#722ed1',
  'Volume 3D': '#1677ff',
  'Volume 4D': '#2f54eb',
  'Volume 5D': '#13c2c2',
  Ultralight: '#fa8c16',
  Hyperlight: '#eb2f96',
  Flawless: '#f5222d',
  Ivylight: '#9254de',
  'Ivylight 3L': '#722ed1',
  'Ivylight 4L': '#531dab',
  'Ivylight 5L': '#391085',
  'Under Mink': '#8c8c8c',
};

const TYPE_LABELS: Record<string, { label: string; color: string }> = {
  Normal: { label: 'Nối mới', color: 'green' },
  Retain: { label: 'Dặm mi', color: 'blue' },
  Fix: { label: 'Sửa/Tháo', color: 'orange' },
  Replace: { label: 'Tháo nối mới', color: 'red' },
};

export default function CatalogBenchmarkTab() {
  const { themeMode } = useTheme();
  const [benchmarks, setBenchmarks] = useState<LashTypeBenchmark[]>([]);
  const [loading, setLoading] = useState(false);
  const [seeding, setSeeding] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [editValues, setEditValues] = useState<{ benchmarkMinutes: number; minMinutes: number; maxMinutes: number }>({
    benchmarkMinutes: 0,
    minMinutes: 0,
    maxMinutes: 0,
  });

  const fetchBenchmarks = useCallback(async () => {
    setLoading(true);
    try {
      const res = await apiClient.catalog.lashBenchmarks.list();
      if (res.success) setBenchmarks(res.data);
    } catch {
      message.error('Không thể tải dữ liệu benchmark');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchBenchmarks();
  }, [fetchBenchmarks]);

  const handleSeed = async () => {
    setSeeding(true);
    try {
      const res = await apiClient.catalog.lashBenchmarks.seed();
      if (res.success) {
        message.success(res.message || 'Seed hoàn tất');
        fetchBenchmarks();
      }
    } catch {
      message.error('Lỗi khi seed benchmark từ Legacy DB');
    } finally {
      setSeeding(false);
    }
  };

  const startEdit = (record: LashTypeBenchmark) => {
    setEditingId(record.id);
    setEditValues({
      benchmarkMinutes: record.benchmarkMinutes,
      minMinutes: record.minMinutes,
      maxMinutes: record.maxMinutes,
    });
  };

  const cancelEdit = () => {
    setEditingId(null);
  };

  const saveEdit = async () => {
    if (!editingId) return;
    try {
      const res = await apiClient.catalog.lashBenchmarks.update(editingId, editValues);
      if (res.success) {
        message.success('Đã cập nhật benchmark');
        setBenchmarks((prev) =>
          prev.map((b) => (b.id === editingId ? { ...b, ...editValues, isAutoGenerated: false } : b))
        );
        setEditingId(null);
      }
    } catch {
      message.error('Lỗi khi cập nhật benchmark');
    }
  };

  const columns = [
    {
      title: 'Loại mi',
      dataIndex: 'lashStyle',
      key: 'lashStyle',
      width: 140,
      render: (style: string) => (
        <Tag color={STYLE_COLORS[style] || '#8c8c8c'} style={{ fontWeight: 600, fontSize: 12 }}>
          {style}
        </Tag>
      ),
      filters: [...new Set(benchmarks.map((b) => b.lashStyle))].map((s) => ({ text: s, value: s })),
      onFilter: (value: any, record: LashTypeBenchmark) => record.lashStyle === value,
    },
    {
      title: 'Loại DV',
      dataIndex: 'serviceType',
      key: 'serviceType',
      width: 120,
      render: (type: string) => {
        const info = TYPE_LABELS[type];
        return info ? <Tag color={info.color}>{info.label}</Tag> : <Tag>{type}</Tag>;
      },
      filters: Object.entries(TYPE_LABELS).map(([key, val]) => ({ text: val.label, value: key })),
      onFilter: (value: any, record: LashTypeBenchmark) => record.serviceType === value,
    },
    {
      title: 'Số sợi',
      dataIndex: 'lashCount',
      key: 'lashCount',
      width: 80,
      align: 'center' as const,
      render: (count: number | null) =>
        count ? (
          <Text strong style={{ fontVariantNumeric: 'tabular-nums' }}>
            {count}
          </Text>
        ) : (
          <Text type="secondary">—</Text>
        ),
      sorter: (a: LashTypeBenchmark, b: LashTypeBenchmark) => (a.lashCount || 0) - (b.lashCount || 0),
    },
    {
      title: (
        <Tooltip title="P50 Median — Thời gian chuẩn trung vị">
          <span>Benchmark (p)</span>
        </Tooltip>
      ),
      dataIndex: 'benchmarkMinutes',
      key: 'benchmarkMinutes',
      width: 120,
      align: 'center' as const,
      sorter: (a: LashTypeBenchmark, b: LashTypeBenchmark) => a.benchmarkMinutes - b.benchmarkMinutes,
      render: (val: number, record: LashTypeBenchmark) => {
        if (editingId === record.id) {
          return (
            <InputNumber
              size="small"
              min={5}
              max={300}
              value={editValues.benchmarkMinutes}
              onChange={(v) => setEditValues((prev) => ({ ...prev, benchmarkMinutes: v || 0 }))}
              style={{ width: 70, fontVariantNumeric: 'tabular-nums' }}
            />
          );
        }
        return (
          <Text strong style={{ fontVariantNumeric: 'tabular-nums', fontSize: 14, color: '#1677ff' }}>
            {val}p
          </Text>
        );
      },
    },
    {
      title: (
        <Tooltip title="P25 — Cận dưới nhanh nhất">
          <span>Min (p)</span>
        </Tooltip>
      ),
      dataIndex: 'minMinutes',
      key: 'minMinutes',
      width: 90,
      align: 'center' as const,
      render: (val: number, record: LashTypeBenchmark) => {
        if (editingId === record.id) {
          return (
            <InputNumber
              size="small"
              min={5}
              max={300}
              value={editValues.minMinutes}
              onChange={(v) => setEditValues((prev) => ({ ...prev, minMinutes: v || 0 }))}
              style={{ width: 70, fontVariantNumeric: 'tabular-nums' }}
            />
          );
        }
        return (
          <Text type="secondary" style={{ fontVariantNumeric: 'tabular-nums' }}>
            {val}p
          </Text>
        );
      },
    },
    {
      title: (
        <Tooltip title="P75 — Cận trên chậm nhất">
          <span>Max (p)</span>
        </Tooltip>
      ),
      dataIndex: 'maxMinutes',
      key: 'maxMinutes',
      width: 90,
      align: 'center' as const,
      render: (val: number, record: LashTypeBenchmark) => {
        if (editingId === record.id) {
          return (
            <InputNumber
              size="small"
              min={5}
              max={300}
              value={editValues.maxMinutes}
              onChange={(v) => setEditValues((prev) => ({ ...prev, maxMinutes: v || 0 }))}
              style={{ width: 70, fontVariantNumeric: 'tabular-nums' }}
            />
          );
        }
        return (
          <Text type="secondary" style={{ fontVariantNumeric: 'tabular-nums' }}>
            {val}p
          </Text>
        );
      },
    },
    {
      title: 'Mẫu',
      dataIndex: 'sampleSize',
      key: 'sampleSize',
      width: 70,
      align: 'center' as const,
      render: (val: number) => (
        <Text type="secondary" style={{ fontVariantNumeric: 'tabular-nums' }}>
          {val}
        </Text>
      ),
      sorter: (a: LashTypeBenchmark, b: LashTypeBenchmark) => a.sampleSize - b.sampleSize,
    },
    {
      title: 'Nguồn',
      dataIndex: 'isAutoGenerated',
      key: 'isAutoGenerated',
      width: 90,
      align: 'center' as const,
      render: (auto: boolean) =>
        auto ? (
          <Tag color="default" style={{ fontSize: 11 }}>
            Auto
          </Tag>
        ) : (
          <Tag color="blue" style={{ fontSize: 11 }}>
            Manual
          </Tag>
        ),
    },
    {
      title: '',
      key: 'actions',
      width: 80,
      render: (_: any, record: LashTypeBenchmark) => {
        if (editingId === record.id) {
          return (
            <Space size={4}>
              <Tooltip title="Lưu">
                <Button
                  type="link"
                  size="small"
                  icon={<CheckOutlined />}
                  onClick={saveEdit}
                  style={{ color: '#52c41a' }}
                />
              </Tooltip>
              <Tooltip title="Hủy">
                <Button
                  type="link"
                  size="small"
                  icon={<CloseOutlined />}
                  onClick={cancelEdit}
                  style={{ color: '#ff4d4f' }}
                />
              </Tooltip>
            </Space>
          );
        }
        return (
          <Tooltip title="Chỉnh sửa">
            <Button type="link" size="small" icon={<EditOutlined />} onClick={() => startEdit(record)} />
          </Tooltip>
        );
      },
    },
  ];

  return (
    <div className="space-y-4">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3">
        <div>
          <Text strong style={{ fontSize: 15 }}>
            Bảng thời gian chuẩn theo loại mi
          </Text>
          <br />
          <Text type="secondary" style={{ fontSize: 12 }}>
            Dữ liệu P25 / P50 (Median) / P75 từ Legacy DB 6 tháng • Dùng cho ETA cá thể hóa
          </Text>
        </div>
        <Space>
          <Button icon={<ReloadOutlined />} onClick={fetchBenchmarks} loading={loading}>
            Tải lại
          </Button>
          <Button
            type="primary"
            icon={<ThunderboltOutlined />}
            onClick={handleSeed}
            loading={seeding}
            style={{ background: '#722ed1', borderColor: '#722ed1' }}
          >
            Tự động tính từ data
          </Button>
        </Space>
      </div>

      <Table
        rowKey="id"
        columns={columns}
        dataSource={benchmarks}
        loading={loading}
        pagination={{
          pageSize: 50,
          showSizeChanger: true,
          pageSizeOptions: ['20', '50', '100'],
          showTotal: (total, range) => `${range[0]}-${range[1]} của ${total} benchmark`,
        }}
        size="small"
        scroll={{ x: 900 }}
        rowClassName={(record) =>
          record.isAutoGenerated ? '' : themeMode === 'dark' ? 'bg-blue-950/20' : 'bg-blue-50/50'
        }
      />
    </div>
  );
}
