import type { CareerProgressionConfig } from '@mos-lab/shared';

export const FALLBACK_CAREER_PROGRESSION_CONFIG: CareerProgressionConfig = {
  version: '2026.2',
  updatedAt: new Date().toISOString(),
  updatedBy: 'System Update',
  cvToCc: {
    minOrders: 300,
    minConsecutiveMonths: 3,
    minTipRatioAboveShop: 0.1,
    maxFixRate: 0.02,
    minHappinessIndex: 0.7,
    maxDisciplinaryViolations: 0,
    trialDurationDays: 30,
    minSelfComboRate: 0.25,
    allowSelfConsultTrial: true,
  },
  ccToFm: {
    minMonthsInRole: 3,
    minMonthlyGoogleReviews: 30,
    maxDisciplinaryViolations: 0,
    weeklyAuditRequired: true,
    minShopComboRate: 0.25,
    minAvgLevel: 10,
  },
  fmToCho: {
    minTargetHitMonths: 3,
    helpLowHiStaffImprove: true,
    maxInventoryLossRate: 0.005,
    minFacilityScore: 95,
    maxChoPerShop: 1,
    maxConsumablesRate: 0.05,
    maxWelcomeBudgetPerNewCustomer: 20000,
    minShopNetMarginForBonus: 0.12,
    gainSharingRatio: 0.2,
  },
  choToBoss: {
    minProfitableMonths: 6,
    minNetProfitMargin: 0.15,
    minMonthlyNewCustomers: 60,
    minStaffEnps: 80,
    requiredSuccessors: {
      fmCount: 1,
      choCount: 1,
    },
  },
  rewardRates: {
    bananaPerFALShort: 15,
    bananaPerFALCcShort: 5,
    ccBonusRatePerLevel: 65,
    tipShareCvRatio: 0.7,
    tipShareCcRatio: 0.2,
    fmMonthlyBananaGrant: 500,
  },
};
