import type { BugReportDetail, BugReportImplementationState } from '@mos-lab/shared';

export const capturedAt = '2026-09-07T00:00:00.000Z';

export function makeDetail(overrides: Partial<BugReportDetail> = {}): BugReportDetail {
  return {
    id: 900001,
    key: 'MOS-BUG-900001',
    requestType: 'BUG',
    featureRequest: null,
    expertDetails: null,
    title: 'Synthetic Inbox regression',
    description: 'Giữ nguyên hành vi chi tiết ticket.',
    status: 'NEW',
    priority: 'P1',
    sourcePath: '/dashboard/bk',
    overlay: null,
    attachmentCount: 0,
    commentCount: 0,
    clarification: { status: 'READY', summary: 'Đủ dữ kiện tổng hợp.', clarifiedAt: capturedAt },
    reopen: null,
    agentProgress: { stage: 'READY_FOR_TRIAGE', note: null, updatedAt: capturedAt },
    implementation: null,
    nextAction: {
      actor: 'DANNY',
      type: 'TRIAGE',
      label: 'Danny cần quyết định',
      detail: 'Xem plan hiện tại.',
      waitingSince: capturedAt,
    },
    reporterExperience: {
      state: 'REVIEWING',
      label: 'Đang xem yêu cầu',
      summary: 'Dữ liệu kiểm thử tổng hợp.',
      nextAction: { label: 'Chờ xử lý', detail: 'Không gửi yêu cầu thật.' },
      updates: [],
    },
    reporter: { id: -71001, displayName: 'QA Reporter', role: 'manager', avatarUrl: null },
    approvedAt: null,
    timeline: {
      reportedAt: capturedAt,
      approvedAt: null,
      startedAt: null,
      fixedAt: null,
      closedAt: null,
      updatedAt: capturedAt,
    },
    createdAt: capturedAt,
    updatedAt: capturedAt,
    businessContext: 'Kết quả đúng đã được ghi nhận.',
    triageNote: 'Ghi chú đã lưu.',
    duplicateOfId: null,
    duplicateOfKey: null,
    approvedBy: null,
    resolvedAt: null,
    closedAt: null,
    context: {
      capturedAt,
      path: '/dashboard/bk',
      query: {},
      pageTitle: 'QA only',
      overlays: [],
      themeMode: 'light',
      viewport: { width: 1440, height: 900, devicePixelRatio: 1 },
      userAgent: 'Synthetic QA',
      online: true,
      timeZone: 'Asia/Ho_Chi_Minh',
      webCommit: null,
      apiCommit: null,
      apiDeployedAt: null,
      recentApiFailures: [],
      recentClientErrors: [],
    },
    resolution: null,
    attachments: [],
    comments: [],
    audits: [],
    ...overrides,
  };
}

export function makeImplementation(
  overrides: Partial<BugReportImplementationState> = {}
): BugReportImplementationState {
  return {
    status: 'FAILED',
    phase: 'FAILED',
    progressLabel: null,
    lastProgressAt: capturedAt,
    progressCount: 1,
    checkpointCount: 0,
    failureCode: 'QUALITY_GATE_FAILED',
    retrySequence: 1,
    canRetryImplementation: false,
    canAuthorizeWorkerRecoveryRetry: false,
    canAuthorizeSchemaRecoveryRetry: false,
    canAuthorizeQualityGateRecoveryRetry: false,
    canAuthorizeBuildLockRecoveryRetry: false,
    failure: null,
    hasRetainedDraft: true,
    startedAt: capturedAt,
    completedAt: capturedAt,
    updatedAt: capturedAt,
    ...overrides,
  };
}
