ALTER TABLE `crm_staff`
  ADD COLUMN `pay_basis` VARCHAR(12) NULL AFTER `hourly_wage`;

CREATE TABLE `crm_holiday_periods` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(50) NOT NULL,
  `name` VARCHAR(160) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `timezone` VARCHAR(50) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',
  `status` VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
  `standard_shift_hours` DOUBLE NOT NULL DEFAULT 9,
  `work_premium_multiplier` DOUBLE NOT NULL DEFAULT 3,
  `paid_leave_multiplier` DOUBLE NOT NULL DEFAULT 1,
  `monthly_standard_days` INTEGER NOT NULL DEFAULT 26,
  `monthly_standard_hours` DOUBLE NOT NULL DEFAULT 234,
  `selection_window_days` INTEGER NOT NULL DEFAULT 90,
  `selection_weights_json` TEXT NOT NULL,
  `notes` TEXT NULL,
  `created_by_staff_id` INTEGER NOT NULL,
  `published_by_staff_id` INTEGER NULL,
  `published_at` DATETIME(0) NULL,
  `payroll_locked_by_staff_id` INTEGER NULL,
  `payroll_locked_at` DATETIME(0) NULL,
  `created_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  `updated_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  UNIQUE INDEX `crm_holiday_periods_code_key`(`code`),
  INDEX `crm_holiday_periods_status_start_date_idx`(`status`, `start_date`),
  INDEX `crm_holiday_periods_start_date_end_date_idx`(`start_date`, `end_date`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `crm_holiday_coverage` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `holiday_id` INTEGER NOT NULL,
  `work_date` DATE NOT NULL,
  `store_id` INTEGER NULL,
  `store_key` VARCHAR(30) NOT NULL,
  `team_code` VARCHAR(30) NOT NULL,
  `shift_start` CHAR(5) NOT NULL,
  `shift_end` CHAR(5) NOT NULL,
  `required_count` INTEGER NOT NULL,
  `notes` TEXT NULL,
  `created_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  `updated_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  UNIQUE INDEX `holiday_coverage_slot`(`holiday_id`, `work_date`, `store_key`, `team_code`, `shift_start`, `shift_end`),
  INDEX `crm_holiday_coverage_holiday_id_work_date_idx`(`holiday_id`, `work_date`),
  PRIMARY KEY (`id`),
  CONSTRAINT `crm_holiday_coverage_holiday_id_fkey` FOREIGN KEY (`holiday_id`) REFERENCES `crm_holiday_periods`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `crm_holiday_roster` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `holiday_id` INTEGER NOT NULL,
  `roster_key` VARCHAR(191) NOT NULL,
  `work_date` DATE NOT NULL,
  `crm_staff_id` INTEGER NULL,
  `legacy_staff_id` INTEGER NULL,
  `imported_name` VARCHAR(160) NULL,
  `display_name` VARCHAR(160) NOT NULL,
  `team_code` VARCHAR(30) NOT NULL,
  `store_id` INTEGER NULL,
  `store_key` VARCHAR(30) NOT NULL,
  `shift_start` CHAR(5) NOT NULL,
  `shift_end` CHAR(5) NOT NULL,
  `status` VARCHAR(24) NOT NULL,
  `nomination_reason` TEXT NULL,
  `decision_reason` TEXT NULL,
  `is_approved_leave` TINYINT NOT NULL DEFAULT 0,
  `nominated_by_staff_id` INTEGER NULL,
  `scheduled_by_staff_id` INTEGER NULL,
  `created_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  `updated_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  UNIQUE INDEX `holiday_roster_key`(`holiday_id`, `roster_key`),
  INDEX `crm_holiday_roster_holiday_id_work_date_status_idx`(`holiday_id`, `work_date`, `status`),
  INDEX `crm_holiday_roster_legacy_staff_id_work_date_idx`(`legacy_staff_id`, `work_date`),
  INDEX `crm_holiday_roster_crm_staff_id_work_date_idx`(`crm_staff_id`, `work_date`),
  PRIMARY KEY (`id`),
  CONSTRAINT `crm_holiday_roster_holiday_id_fkey` FOREIGN KEY (`holiday_id`) REFERENCES `crm_holiday_periods`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `crm_holiday_candidate_snapshots` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `holiday_id` INTEGER NOT NULL,
  `work_date` DATE NOT NULL,
  `crm_staff_id` INTEGER NULL,
  `legacy_staff_id` INTEGER NOT NULL,
  `display_name` VARCHAR(160) NOT NULL,
  `avatar_url` VARCHAR(500) NULL,
  `team_code` VARCHAR(30) NOT NULL,
  `store_id` INTEGER NULL,
  `store_key` VARCHAR(30) NOT NULL,
  `score_window_from` DATE NOT NULL,
  `score_window_to` DATE NOT NULL,
  `total_score` DOUBLE NULL,
  `data_sufficient` TINYINT NOT NULL DEFAULT 0,
  `data_coverage_reason` VARCHAR(255) NULL,
  `metrics_json` LONGTEXT NOT NULL,
  `explanation_json` TEXT NOT NULL,
  `generated_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  UNIQUE INDEX `holiday_candidate_staff_day`(`holiday_id`, `work_date`, `legacy_staff_id`),
  INDEX `holiday_candidate_period_score_idx`(`holiday_id`, `work_date`, `total_score`),
  PRIMARY KEY (`id`),
  CONSTRAINT `crm_holiday_candidate_snapshots_holiday_id_fkey` FOREIGN KEY (`holiday_id`) REFERENCES `crm_holiday_periods`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `crm_staff_performance_events` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `crm_staff_id` INTEGER NULL,
  `legacy_staff_id` INTEGER NULL,
  `display_name` VARCHAR(160) NOT NULL,
  `event_type` VARCHAR(30) NOT NULL,
  `source` VARCHAR(20) NOT NULL,
  `severity` VARCHAR(12) NOT NULL,
  `occurred_at` DATETIME(0) NOT NULL,
  `store_id` INTEGER NULL,
  `store_key` VARCHAR(30) NULL,
  `related_order_id` INTEGER NULL,
  `related_ticket_id` INTEGER NULL,
  `evidence_url` TEXT NULL,
  `note` TEXT NOT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'PENDING',
  `created_by_staff_id` INTEGER NOT NULL,
  `verified_by_staff_id` INTEGER NULL,
  `verified_at` DATETIME(0) NULL,
  `rejection_reason` TEXT NULL,
  `created_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  `updated_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  INDEX `crm_staff_performance_events_legacy_staff_id_occurred_at_idx`(`legacy_staff_id`, `occurred_at`),
  INDEX `crm_staff_performance_events_crm_staff_id_occurred_at_idx`(`crm_staff_id`, `occurred_at`),
  INDEX `staff_perf_status_type_date_idx`(`status`, `event_type`, `occurred_at`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `crm_holiday_payroll_ledger` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `holiday_id` INTEGER NOT NULL,
  `roster_id` INTEGER NOT NULL,
  `work_date` DATE NOT NULL,
  `crm_staff_id` INTEGER NULL,
  `legacy_staff_id` INTEGER NULL,
  `display_name` VARCHAR(160) NOT NULL,
  `team_code` VARCHAR(30) NOT NULL,
  `store_key` VARCHAR(30) NOT NULL,
  `roster_status` VARCHAR(24) NOT NULL,
  `pay_basis` VARCHAR(12) NULL,
  `ledger_status` VARCHAR(16) NOT NULL DEFAULT 'EXCEPTION',
  `attendance_source` VARCHAR(40) NOT NULL,
  `actual_minutes` INTEGER NOT NULL DEFAULT 0,
  `actual_hours` DOUBLE NOT NULL DEFAULT 0,
  `standard_shift_hours` DOUBLE NOT NULL,
  `hourly_rate` INTEGER NOT NULL DEFAULT 0,
  `base_holiday_amount` INTEGER NOT NULL DEFAULT 0,
  `holiday_premium_amount` INTEGER NOT NULL DEFAULT 0,
  `holiday_total_value` INTEGER NOT NULL DEFAULT 0,
  `payroll_addition_amount` INTEGER NOT NULL DEFAULT 0,
  `base_included_in_monthly_salary` TINYINT NOT NULL DEFAULT 0,
  `exception_code` VARCHAR(50) NULL,
  `exception_message` TEXT NULL,
  `calculation_version` VARCHAR(30) NOT NULL,
  `locked_at` DATETIME(0) NULL,
  `locked_by_staff_id` INTEGER NULL,
  `created_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  `updated_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  UNIQUE INDEX `crm_holiday_payroll_ledger_roster_id_key`(`roster_id`),
  INDEX `holiday_ledger_period_date_status_idx`(`holiday_id`, `work_date`, `ledger_status`),
  INDEX `crm_holiday_payroll_ledger_legacy_staff_id_work_date_idx`(`legacy_staff_id`, `work_date`),
  PRIMARY KEY (`id`),
  CONSTRAINT `crm_holiday_payroll_ledger_holiday_id_fkey` FOREIGN KEY (`holiday_id`) REFERENCES `crm_holiday_periods`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `crm_holiday_payroll_ledger_roster_id_fkey` FOREIGN KEY (`roster_id`) REFERENCES `crm_holiday_roster`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `crm_holiday_audit_logs` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `holiday_id` INTEGER NOT NULL,
  `action` VARCHAR(50) NOT NULL,
  `entity_type` VARCHAR(50) NOT NULL,
  `entity_id` INTEGER NULL,
  `actor_staff_id` INTEGER NOT NULL,
  `reason` TEXT NULL,
  `before_json` LONGTEXT NULL,
  `after_json` LONGTEXT NULL,
  `created_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  INDEX `crm_holiday_audit_logs_holiday_id_created_at_idx`(`holiday_id`, `created_at`),
  INDEX `crm_holiday_audit_logs_actor_staff_id_created_at_idx`(`actor_staff_id`, `created_at`),
  PRIMARY KEY (`id`),
  CONSTRAINT `crm_holiday_audit_logs_holiday_id_fkey` FOREIGN KEY (`holiday_id`) REFERENCES `crm_holiday_periods`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `crm_holiday_payroll_adjustments` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `holiday_id` INTEGER NOT NULL,
  `ledger_id` INTEGER NOT NULL,
  `amount` INTEGER NOT NULL,
  `reason` TEXT NOT NULL,
  `created_by_staff_id` INTEGER NOT NULL,
  `created_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  INDEX `crm_holiday_payroll_adjustments_holiday_id_created_at_idx`(`holiday_id`, `created_at`),
  INDEX `crm_holiday_payroll_adjustments_ledger_id_created_at_idx`(`ledger_id`, `created_at`),
  PRIMARY KEY (`id`),
  CONSTRAINT `crm_holiday_payroll_adjustments_holiday_id_fkey` FOREIGN KEY (`holiday_id`) REFERENCES `crm_holiday_periods`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `crm_holiday_payroll_adjustments_ledger_id_fkey` FOREIGN KEY (`ledger_id`) REFERENCES `crm_holiday_payroll_ledger`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
